#pragma once

#define SOCKET_TYPE SOCK_STREAM // TCP
#define ADDRESS_FAMILY AF_INET	// IPv4
#define ADDRESS_IP INADDR_ANY	// Listen on all interfaces
#define IRCHOSTNAME "www.irclevrai.com"
#define MAX_CONNECTING_CLIENTS 10
#define BUFFER_SIZE 1024
#define RPL_INVITING 341
#define ERR_NOSUCHNICK 401
#define ERR_NOSUCHCHANNEL 403
#define ERR_UNKNOWNCOMMAND 421
#define ERR_NOTONCHANNEL 442
#define ERR_NEEDMOREPARAMS 461
#define ERR_ALREADYREGISTERED 462
#define ERR_CHANOPRIVSNEEDED 482
